name: STGR Wiki Backup

on:
  workflow_dispatch:

  schedule:
    - cron: "0 15 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install requests pynacl

      - name: Run backup
        env:
          ATWIKI_CLIENT_ID: ${{ secrets.ATWIKI_CLIENT_ID }}
          ATWIKI_CLIENT_SECRET: ${{ secrets.ATWIKI_CLIENT_SECRET }}
          ATWIKI_REFRESH_TOKEN: ${{ secrets.ATWIKI_REFRESH_TOKEN }}
          STGR_GITHUB_PAT: ${{ secrets.STGR_GITHUB_PAT }}
        run: |
          python backup.py

      - name: Commit and push backup
        run: |
          git config user.name "STGR Wiki Backup"
          git config user.email "actions@github.com"

          git add backup/

          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "Update STGR Wiki backup"
            git push
          fi
